<link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico"/>
<link rel="canonical" href="https://trimaran.org"/>
<meta property="og:site_name" content="Trimaran"/>
<meta property="og:title" content="Trimaran"/>
<meta property="og:url" content="https://trimaran.org"/>
<meta property="og:type" content="website"/>
<meta property="og:image" content="images/trimaran.png"/>
<meta property="og:image:width" content="1000"/>
<meta property="og:image:height" content="1019"/>
<meta itemprop="name" content="Trimaran"/>
<meta itemprop="url" content="https://trimaran.org"/>
<meta itemprop="thumbnailUrl" content="images/trimaran.png"/>
<meta name="twitter:title" content="Trimaran"/>
<meta name="twitter:image" content="images/trimaran.org"/>
<meta name="twitter:url" content="https://trimaran.org"/>
<meta name="twitter:card" content="summary"/>
<meta name="description" content="" />
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Ubuntu:400,700,700i,400i"/>
<link rel="stylesheet" type="text/css" href="style.css"/>

<script>
function toggleNav() {
  var m = document.getElementById("sidecarNav");
  var b = document.getElementById("body");
  if (m.closed === undefined || m.closed) {
    b.classList.add("mobile-nav-open")
    m.classList.add("mobile-nav-open")
    m.closed = false;
  } else {
    b.classList.remove("mobile-nav-open")
    m.classList.remove("mobile-nav-open")
    m.closed = true;
  }
}
</script>
