<body text="#000000">
  <div id="container">
  <table width="100%" height="100%" cellpadding="0" cellspacing="0" border="0">
    <tr>
    <td background="images/background-left.gif" width="98">&nbsp;</td>
    <td valign=top>
      <div id="title">
      <center><table cellspacing=0 cellpadding=0 border=0><tr><td>
      <img src="images/trimaran-logo.png" height="100" width="400" align="center"> 
      </td></tr></table>
      </center>
      </div>
      <div id="menu">
        <ul id="menu">
          <li>
            <a href="index.html">home</a>
          </li>
          <li>
            <a href="news.html"><b>news</b></a>
          </li>
          <li>
            <a href="overview.html">overview</a>
          </li>
          <li>
            <a href="documentation.html"><b>documentation</b></a>
          </li>
          <li>
            <a href="requirements.html">requirements</a>
          </li>
         <li>
            <a href="download.html"><b>download</b></a>
          </li>
         <li>
            <a href="support.html">support</a>
          </li>
         <li>
            <a href="contribute.html">contribute</a>
         </li>
       </ul>
      </div>
      <br>
      <div id="main">
